# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowTo' do
  use_frameworks!

  # Pods for HowTo
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'

end
